name: On Pull Request

"on":
  pull_request:
    branches:
      - "master"

jobs:
  inspection_and_tests:
    name: Inspection and Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node: ["16", "18"]
    env:
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm dependencies
        run: npm install
      - name: Run format check with prettier
        run: npm run format:check
      - name: Run lint check
        run: npm run lint
      - name: Run static-pages build check
        run: npm run tool:scully

  build_and_deploy_testbed_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    name: Build and deploy on Firebase - testbed preview
    needs: [inspection_and_tests]
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node: ["18"]
    env:
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Build static files
        run: npm run tool:scully
      - name: Deploy on Firebase - testbed preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEATHER_RADAR_C13DF }}"
          projectId: weather-radar-c13df
          target: testbed
