name: "On Push"

"on":
  push:
    branches:
      - "*"
      - "*/*"

jobs:
  inspection_and_tests:
    name: Inspection and Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        node: ["14", "16"]
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm dependencies
        run: npm install
      - name: Run format check with prettier
        run: npm run format:check
      - name: Run lint check
        run: npm run lint
      - name: Run static-pages build check
        run: npm run tool:scully
